name: Polarbeards
favicon: null
layout_spectrum: 0.17602
typography_spectrum: 0.22585
title: Beard Care for Extreme Conditions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a7a9ac'
    - '#58585a'
    - '#0077a4'
    - '#3a3a3c'
  brandStrength: 0.5
  lightness: 0.4351651417091489
  saturation: 0.7292414922267199
  rhythmicContrast: 0.3920738217420876
purpose: []
