name: Polarbeards
favicon: null
layout_spectrum: 0.25712
typography_spectrum: 0.22585
title: Beard Care for Extreme Conditions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a7a9ac'
    - '#58585a'
    - '#0077a4'
    - '#3a3a3c'
  brandStrength: 0.6875
  lightness: 0
  saturation: 0.0625
  rhythmicContrast: 0
purpose: []
