name: Polarbeards
favicon: null
layout_spectrum: 0.01983486651442945
typography_spectrum: 0.24051636015065014
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8270910298451781
  lightness: 0.4351651417091489
  saturation: 0.7292414922267199
  rhythmicContrast: 0.3920738217420876
purpose: []
